### ISSUE TITLE
Inferencing for a receptor protein

### ISSUE THREAD

**Issue by chiragmathur27** [Wangchentong/Proteus#5]
Hey,

I wanted to know how to run a inferencing code for a particular protein.
As far as I have explored , we have to make changes in the inference.yaml
But need to understand how to give inputs for the following keys,  Hotspot and contigs, prefix.

Hope to here from you soon.

**Comment by pengzhangzhi** [comment]
Hey current proteus is an unconditional generator, can't specify anything : (

**Comment by chiragmathur27** [comment]
Can we give reference pdb for unconditional generation.
