### ISSUE TITLE
Regarding the paper "Towards Deep Learning Sequence-Structure Co-Generation for Protein Design."

### ISSUE THREAD

**Issue by MingYangi** [Wangchentong/Proteus#6]
Hello author, I have been following your paper "Towards deep learning sequence-structure co-generation for protein design" recently, and it's very well summarized; I found it quite inspiring. I have a question for you: Are you familiar with the paper "protein sequence and structure co-design with equivariant translation"? Why isn't this paper included in your review? In your opinion, which category of co-design does this paper fall into? Hybrid co-generation models or All-atom co-generation models?

**Comment by Wangchentong** [comment]
Hi MingYang,

Thank you for your interest in our recent review paper. I noticed the paper you mentioned as soon as it was published on arXiv. In my view, it fall into simple one-shot generation, as a repetitive work to RFjoint, employing a one-shot prediction of both structure and sequence. However, as a common drawback of one-shot generation, its capabilities don’t extend much beyond inpainting, as it lacks a generative process for sequence or structure (such as diffusion, flow matching, or masked generative models). As mentioned in the review, these approaches do not demonstrate the ability to generate proteins from scratch, only serve for a conceptual strategy of co-design with limited application.

Thank you for pointing this out. We will consider citing this paper in the background section on co-design when the review is officially published.

**Comment by MingYangi** [comment]
Thank you very much, author! 

I have gained a lot from it. However, I would like to ask you another question. Do you think the reason ProtSeed is not considered de novo design is because it uses secondary structures and contact maps as conditions for generation, and therefore requires some pre-set conditions that affect the novelty of the generated proteins? How do you define de novo protein design? 

Additionally, could you please leave your email or other contact information? I'm currently researching in this area and would particularly like to learn from you. Thank you once again!

**Comment by Wangchentong** [comment]
The boundary between protein design and de novo protein design is somewhat blurred. To clarify, I’m not suggesting that ProtSeed isn’t part of de novo protein design. However, what I’m trying to emphasize is that ProtSeed and similar one-shot generation methods function more like prediction models, relying heavily on strong conditional input of the overall protein topology. Conditional generation has many impressive applications as well, but in our review, we focus more on models with true generative capabilities.
